branches:
  only:
    - master

language: rust

cache: cargo

before_script:
  - rustup component add rustfmt-preview

script:
  - cargo fmt -- --write-mode=diff
  - cargo build
  - cargo test

addons:
  apt:
    packages:
      - libgtk-3-dev
      - libasound2-dev
