[package]
name = "yotredash"
version = "0.1.0"
authors = ["Ash Levy <ashy.of.ren@gmail.com>"]

[dependencies]
clap = "2.26.0"
env_logger = "0.4.3"
derive-error-chain = "0.11.0"
error-chain = "0.11.0"
freetype-rs = "0.14.0"
image = "0.15.0"
log = "0.3.8"
owning_ref = "0.3.3"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
time = "0.1.38"
winit = "0.7.6"

# Needed by opengl feature
glium = { version = "0.17.0", optional = true }

[target.'cfg(unix)'.dependencies]
signal = "0.4.0"

[features]
default = ["opengl"]
opengl = ["glium"]
