[package]
name = "yotredash"
version = "0.1.0"
authors = ["Ash Levy <ashy.of.ren@gmail.com>"]

[dependencies]
clap = "2.26.0"
env_logger = "0.4.3"
glium = "0.17.0"
image = "0.15.0"
log = "0.3.8"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
time = "0.1.38"

[target.'cfg(unix)'.dependencies]
signal = "0.4.0"
