[package]
name = "yotredash"
version = "0.1.0"
authors = ["Ash Levy <ashy.of.ren@gmail.com>"]

[dependencies]
glium = "0.17.0"
clap = "2.26.0"
time = "0.1.38"
image = "0.15.0"
log = "0.3.8"
env_logger = "0.4.3"
