[package]
name = "yotredash"
version = "0.1.0"
authors = ["Ash Levy <ashy.of.ren@gmail.com>"]

[dependencies]
clap = "2.26.0"
derive-error-chain = "0.11.0"
env_logger = "0.4.3"
error-chain = "0.11.0"
font-loader = "0.4.2"
freetype-rs = "0.15.0"
image = "0.15.0"
log = "0.3.8"
nfd = { git = "https://github.com/ashkitten/nfd-rs" }
owning_ref = "0.3.3"
rect_packer = "0.2.1"
serde = "1.0.11"
serde_derive = "1.0.11"
serde_yaml = "0.7.1"
time = "0.1.38"
winit = "0.7.6"

# Needed by opengl feature
glium = { version = "0.17.0", optional = true }

[target.'cfg(unix)'.dependencies]
signal = "0.4.0"

[features]
default = ["opengl"]
opengl = ["glium"]

[replace]
"servo-fontconfig-sys:4.0.4" = { git = "https://github.com/ashkitten/libfontconfig" }
