[package]
name = "yotredash"
version = "0.1.0"
authors = ["Ash Levy <ashy.of.ren@gmail.com>"]

[dependencies]
clap = "2.29.0"
derive-error-chain = "0.11.0"
env_logger = "0.4.3"
error-chain = "0.11.0"
font-loader = "0.5.0"
freetype-rs = "0.16.0"
log = "0.3.8"
nfd = { git = "https://github.com/ashkitten/nfd-rs", branch = "dev" }
owning_ref = "0.3.3"
rect_packer = "0.2.1"
serde = "1.0.26"
serde_derive = "1.0.26"
serde_yaml = "0.7.3"
time = "0.1.38"
winit = "0.9.0"

# Needed by opengl feature
glium = { version = "0.19.0", optional = true }

# Needed by image feature
image = { version = "0.18.0", optional = true }
num-rational = { version = "0.1.40", optional = true }

[target.'cfg(unix)'.dependencies]
signal = "0.4.0"

[dev-dependencies]
glob = "0.2.11"

[features]
default = ["opengl", "image-src"]
opengl = ["glium"]
image-src = ["image", "num-rational"]

[replace]
"servo-fontconfig-sys:4.0.4" = { git = "https://github.com/ashkitten/libfontconfig" }
