attributes_on_same_line_as_field = false
attributes_on_same_line_as_variant = false
fn_args_density = "Compressed"
fn_call_width = 120
max_width = 120
normalize_comments = true
reorder_imported_names = true
reorder_imports = true
reorder_imports_in_group = true
